version: "3.9"

services:

  kannel-simulator:

    container_name: kannel-simulator
    build: .
    image: kannel-simulator:1.0.0


    environment:
      - id=1
      - DISABLE-DLR-HANDOVER=false

    restart: unless-stopped

    ports:
      - "35001:8080"

    volumes:
      - ./logs:/opt/tomcat/logs
      - ./fallback_files:/opt/tomcat/fallback_files


